name: Save Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  save:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull svftools/teaching-software-verification:latest

      - name: Save Docker image to tarball
        run: docker save svftools/teaching-software-verification:latest -o svf-image.tar

      - name: Debug Tar File
        run: |
          echo "Checking output:"
          ls -lh svf-image.tar

      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: svf-image-tar
          path: svf-image.tar
