name: Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  save-docker-image:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker pull svftools/teaching-software-verification:latest

    - name: Save Docker image as tar
      run: docker save svftools/teaching-software-verification:latest -o svf-image.tar

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="docker-image-$(date +%Y%m%d%H%M%S)"
        gh release create "$tag_name" svf-image.tar -t "$tag_name" -n "Auto upload docker image tar"
